### ISSUE TITLE
Hexcells Level Clipper doesn't show up under Greasemonkey quick-access(?) panel

### ISSUE THREAD

**Issue by edderiofer** [oprypin/userscripts#1]
As per the title. The userscript doesn't even show up when I open up the GreaseMonkey panel on Reddit, though it shows up on the GreaseMonkey dashboard. I'm currently using Chrome 69.0.3497.100.

It also seems to no longer work on puzzles where it previously did work. I'm wondering if this is a change in Chrome or Reddit.

**Comment by oprypin** [comment]
Wait what? Greasemonkey isn't on Chrome 🤔

**Comment by oprypin** [comment]
Works for me on Chromium 69.0.3497.100 and Tampermonkey.
Please clarify regarding my previous point.

**Comment by edderiofer** [comment]
Oops, I did mean Tampermonkey.
________________________________

**Comment by oprypin** [comment]
Could be a non-matching URL (old.reddit.com???)
I have this URL:
https://www.reddit.com/r/hexcellslevels/comments/9luogd/level_pack_ambiguous_clues_2_easyhard/
What about you?

**Comment by edderiofer** [comment]
Ah, that'd be why; I'm using old.reddit.com. Any chance of updating the script to make that match?
________________________________
